[flow]
strip_tls_handshake = ${STRIP_TLS_HANDSHAKES}

[flow.source_a.Empirical]
path = "${FLOWS}"
flow_filter = "tlsDataPackets >= ${FEATURE_PACKET_HORIZON}"

[model]
model_assumptions = "${MODEL_ASSUMPTIONS}"
pseudocount = 1.0
